kind: PersistentVolume
apiVersion: v1
metadata:
  name: prometheus-data
  labels:
    type: local
    app: prometheus
spec:
  storageClassName: local
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
      # directory location on host
      path: /data
      # this field is optional
      type: Directory